name: Deploy 
on:
  push:
    branches: [ "main" ]
env:
  buildNumber: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jpoehnelt/secrets-sync-action@v1.4.1
      with:
        SECRETS: |
          ^FOO$
          ^FOO2$
        REPOSITORIES: |
          ^techgoogle1/test2$
        DRY_RUN: false
        environment: SIT
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
        CONCURRENCY: 10
      env:
       FOO: ${{secrets.FOO}}
       FOO2: ${{secrets.FOO2}}
