name: Deploy 
on:
  push:
    branches: [ "main" ]
env:
  buildNumber: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: google/secrets-sync-action@v1.7.0
      with:
        SECRETS: |
          ^FOO$
          ^SIT_TEST$
        REPOSITORIES: |
          ^techgoogle1/test2$
        DRY_RUN: false
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN_CLASSIC }}
        GITHUB_API_URL: ${{ secrets.CUSTOM_GITHUB_API_URL }}
        CONCURRENCY: 10
      env:
       FOO: ${{github.run_id}}
       FOOBAR: BAZ
